version: '3.1'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'

  consul:
    image: hashicorp/consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'

